# This script will be responsible for running on another linux laptop environment to keep track of passcodes.
# The Pi will communicate with this laptop as to confirm passcode and grant access.
# In order to make life a bit easier, we have implemented a web scrape library that will help us with updating the current passcode.

from webbot import Browser
from datetime import datetime
import time

idPW = {"alexsolz" : "", "devinwu" : "", "paulpaik" : ""}

while True:
    # Check through each user information to fetch password generated by website.
    for key, value in idPW.items():
        web = Browser(showWindow=False)
        web.go_to('cs.colostate.edu/~alexsolz/tincup/login.php')
        web.type(key, into='username')
        tmpPW = ""
        if "alex" in key:
            tmpPW = "alex123"
        elif "devin" in key:
            tmpPW = "devin123"
        elif "paul" in key:
            tmpPW = "paul123"
        web.type(tmpPW, into='password')
        web.click('Submit')

        # Scrape the source code to parse out current passcode information before expiration.
        tmpSource = web.get_page_source()
        tmpList = tmpSource.split(" ")

        # Parse out passcode data and update to file.
        startIndex = tmpList[70].strip("\n").find(">")
        lastIndex = tmpList[70].strip("\n").find("<")
        idPW[key] = tmpList[70][startIndex + 1:lastIndex]
        web.click('Sign Out')
        web.close_current_tab()
    
    with open("pwInfo.txt", "w") as data:
        for key, value in idPW.items():
            data.write(key + " " + idPW[key] + "\n")
        data.close()

    now = datetime.now()
    currentTime = now.strftime("%H:%M:%S")
    print("Current time is: " + currentTime)
    print(idPW)
    time.sleep(5)
